/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type ResourcesAPI interface {

	/*
	GetAllResourcesResourcesGet Get All Resources

	Fetch resources details.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetAllResourcesResourcesGetRequest
	*/
	GetAllResourcesResourcesGet(ctx context.Context) ApiGetAllResourcesResourcesGetRequest

	// GetAllResourcesResourcesGetExecute executes the request
	//  @return DataPageResourceSchema
	GetAllResourcesResourcesGetExecute(r ApiGetAllResourcesResourcesGetRequest) (*DataPageResourceSchema, *http.Response, error)

	/*
	GetResourcesResourcesCodeGet Get Resources

	Retrieve the details of a resource.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param code The code of the resource.
	@return ApiGetResourcesResourcesCodeGetRequest
	*/
	GetResourcesResourcesCodeGet(ctx context.Context, code string) ApiGetResourcesResourcesCodeGetRequest

	// GetResourcesResourcesCodeGetExecute executes the request
	//  @return ResourceResponseSchema
	GetResourcesResourcesCodeGetExecute(r ApiGetResourcesResourcesCodeGetRequest) (*ResourceResponseSchema, *http.Response, error)
}

// ResourcesAPIService ResourcesAPI service
type ResourcesAPIService service

type ApiGetAllResourcesResourcesGetRequest struct {
	ctx context.Context
	ApiService ResourcesAPI
	minLevel *int32
	maxLevel *int32
	skill *string
	drop *string
	page *int32
	size *int32
}

// Skill minimum level.
func (r ApiGetAllResourcesResourcesGetRequest) MinLevel(minLevel int32) ApiGetAllResourcesResourcesGetRequest {
	r.minLevel = &minLevel
	return r
}

// Skill maximum level.
func (r ApiGetAllResourcesResourcesGetRequest) MaxLevel(maxLevel int32) ApiGetAllResourcesResourcesGetRequest {
	r.maxLevel = &maxLevel
	return r
}

// The code of the skill.
func (r ApiGetAllResourcesResourcesGetRequest) Skill(skill string) ApiGetAllResourcesResourcesGetRequest {
	r.skill = &skill
	return r
}

// Item code of the drop.
func (r ApiGetAllResourcesResourcesGetRequest) Drop(drop string) ApiGetAllResourcesResourcesGetRequest {
	r.drop = &drop
	return r
}

// Page number
func (r ApiGetAllResourcesResourcesGetRequest) Page(page int32) ApiGetAllResourcesResourcesGetRequest {
	r.page = &page
	return r
}

// Page size
func (r ApiGetAllResourcesResourcesGetRequest) Size(size int32) ApiGetAllResourcesResourcesGetRequest {
	r.size = &size
	return r
}

func (r ApiGetAllResourcesResourcesGetRequest) Execute() (*DataPageResourceSchema, *http.Response, error) {
	return r.ApiService.GetAllResourcesResourcesGetExecute(r)
}

/*
GetAllResourcesResourcesGet Get All Resources

Fetch resources details.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetAllResourcesResourcesGetRequest
*/
func (a *ResourcesAPIService) GetAllResourcesResourcesGet(ctx context.Context) ApiGetAllResourcesResourcesGetRequest {
	return ApiGetAllResourcesResourcesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return DataPageResourceSchema
func (a *ResourcesAPIService) GetAllResourcesResourcesGetExecute(r ApiGetAllResourcesResourcesGetRequest) (*DataPageResourceSchema, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DataPageResourceSchema
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAPIService.GetAllResourcesResourcesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/resources/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.minLevel != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "min_level", r.minLevel, "")
	}
	if r.maxLevel != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "max_level", r.maxLevel, "")
	}
	if r.skill != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "skill", r.skill, "")
	}
	if r.drop != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "drop", r.drop, "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "")
	} else {
		var defaultValue int32 = 1
		r.page = &defaultValue
	}
	if r.size != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "size", r.size, "")
	} else {
		var defaultValue int32 = 50
		r.size = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetResourcesResourcesCodeGetRequest struct {
	ctx context.Context
	ApiService ResourcesAPI
	code string
}

func (r ApiGetResourcesResourcesCodeGetRequest) Execute() (*ResourceResponseSchema, *http.Response, error) {
	return r.ApiService.GetResourcesResourcesCodeGetExecute(r)
}

/*
GetResourcesResourcesCodeGet Get Resources

Retrieve the details of a resource.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param code The code of the resource.
 @return ApiGetResourcesResourcesCodeGetRequest
*/
func (a *ResourcesAPIService) GetResourcesResourcesCodeGet(ctx context.Context, code string) ApiGetResourcesResourcesCodeGetRequest {
	return ApiGetResourcesResourcesCodeGetRequest{
		ApiService: a,
		ctx: ctx,
		code: code,
	}
}

// Execute executes the request
//  @return ResourceResponseSchema
func (a *ResourcesAPIService) GetResourcesResourcesCodeGetExecute(r ApiGetResourcesResourcesCodeGetRequest) (*ResourceResponseSchema, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResourceResponseSchema
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ResourcesAPIService.GetResourcesResourcesCodeGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/resources/{code}"
	localVarPath = strings.Replace(localVarPath, "{"+"code"+"}", url.PathEscape(parameterValueToString(r.code, "code")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
