/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DepositWithdrawGoldSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DepositWithdrawGoldSchema{}

// DepositWithdrawGoldSchema struct for DepositWithdrawGoldSchema
type DepositWithdrawGoldSchema struct {
	// Quantity of gold.
	Quantity int32 `json:"quantity"`
}

type _DepositWithdrawGoldSchema DepositWithdrawGoldSchema

// NewDepositWithdrawGoldSchema instantiates a new DepositWithdrawGoldSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepositWithdrawGoldSchema(quantity int32) *DepositWithdrawGoldSchema {
	this := DepositWithdrawGoldSchema{}
	this.Quantity = quantity
	return &this
}

// NewDepositWithdrawGoldSchemaWithDefaults instantiates a new DepositWithdrawGoldSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepositWithdrawGoldSchemaWithDefaults() *DepositWithdrawGoldSchema {
	this := DepositWithdrawGoldSchema{}
	return &this
}

// GetQuantity returns the Quantity field value
func (o *DepositWithdrawGoldSchema) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *DepositWithdrawGoldSchema) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *DepositWithdrawGoldSchema) SetQuantity(v int32) {
	o.Quantity = v
}

func (o DepositWithdrawGoldSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DepositWithdrawGoldSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quantity"] = o.Quantity
	return toSerialize, nil
}

func (o *DepositWithdrawGoldSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDepositWithdrawGoldSchema := _DepositWithdrawGoldSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDepositWithdrawGoldSchema)

	if err != nil {
		return err
	}

	*o = DepositWithdrawGoldSchema(varDepositWithdrawGoldSchema)

	return err
}

type NullableDepositWithdrawGoldSchema struct {
	value *DepositWithdrawGoldSchema
	isSet bool
}

func (v NullableDepositWithdrawGoldSchema) Get() *DepositWithdrawGoldSchema {
	return v.value
}

func (v *NullableDepositWithdrawGoldSchema) Set(val *DepositWithdrawGoldSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableDepositWithdrawGoldSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableDepositWithdrawGoldSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepositWithdrawGoldSchema(val *DepositWithdrawGoldSchema) *NullableDepositWithdrawGoldSchema {
	return &NullableDepositWithdrawGoldSchema{value: val, isSet: true}
}

func (v NullableDepositWithdrawGoldSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepositWithdrawGoldSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


