/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ItemResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemResponseSchema{}

// ItemResponseSchema struct for ItemResponseSchema
type ItemResponseSchema struct {
	Data SingleItemSchema `json:"data"`
}

type _ItemResponseSchema ItemResponseSchema

// NewItemResponseSchema instantiates a new ItemResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemResponseSchema(data SingleItemSchema) *ItemResponseSchema {
	this := ItemResponseSchema{}
	this.Data = data
	return &this
}

// NewItemResponseSchemaWithDefaults instantiates a new ItemResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemResponseSchemaWithDefaults() *ItemResponseSchema {
	this := ItemResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *ItemResponseSchema) GetData() SingleItemSchema {
	if o == nil {
		var ret SingleItemSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ItemResponseSchema) GetDataOk() (*SingleItemSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ItemResponseSchema) SetData(v SingleItemSchema) {
	o.Data = v
}

func (o ItemResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ItemResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItemResponseSchema := _ItemResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varItemResponseSchema)

	if err != nil {
		return err
	}

	*o = ItemResponseSchema(varItemResponseSchema)

	return err
}

type NullableItemResponseSchema struct {
	value *ItemResponseSchema
	isSet bool
}

func (v NullableItemResponseSchema) Get() *ItemResponseSchema {
	return v.value
}

func (v *NullableItemResponseSchema) Set(val *ItemResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableItemResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableItemResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemResponseSchema(val *ItemResponseSchema) *NullableItemResponseSchema {
	return &NullableItemResponseSchema{value: val, isSet: true}
}

func (v NullableItemResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


