/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CharacterFightDataSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharacterFightDataSchema{}

// CharacterFightDataSchema struct for CharacterFightDataSchema
type CharacterFightDataSchema struct {
	// Cooldown details.
	Cooldown CooldownSchema `json:"cooldown"`
	// Fight details.
	Fight FightSchema `json:"fight"`
	// Player details.
	Character CharacterSchema `json:"character"`
}

type _CharacterFightDataSchema CharacterFightDataSchema

// NewCharacterFightDataSchema instantiates a new CharacterFightDataSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacterFightDataSchema(cooldown CooldownSchema, fight FightSchema, character CharacterSchema) *CharacterFightDataSchema {
	this := CharacterFightDataSchema{}
	this.Cooldown = cooldown
	this.Fight = fight
	this.Character = character
	return &this
}

// NewCharacterFightDataSchemaWithDefaults instantiates a new CharacterFightDataSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterFightDataSchemaWithDefaults() *CharacterFightDataSchema {
	this := CharacterFightDataSchema{}
	return &this
}

// GetCooldown returns the Cooldown field value
func (o *CharacterFightDataSchema) GetCooldown() CooldownSchema {
	if o == nil {
		var ret CooldownSchema
		return ret
	}

	return o.Cooldown
}

// GetCooldownOk returns a tuple with the Cooldown field value
// and a boolean to check if the value has been set.
func (o *CharacterFightDataSchema) GetCooldownOk() (*CooldownSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cooldown, true
}

// SetCooldown sets field value
func (o *CharacterFightDataSchema) SetCooldown(v CooldownSchema) {
	o.Cooldown = v
}

// GetFight returns the Fight field value
func (o *CharacterFightDataSchema) GetFight() FightSchema {
	if o == nil {
		var ret FightSchema
		return ret
	}

	return o.Fight
}

// GetFightOk returns a tuple with the Fight field value
// and a boolean to check if the value has been set.
func (o *CharacterFightDataSchema) GetFightOk() (*FightSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fight, true
}

// SetFight sets field value
func (o *CharacterFightDataSchema) SetFight(v FightSchema) {
	o.Fight = v
}

// GetCharacter returns the Character field value
func (o *CharacterFightDataSchema) GetCharacter() CharacterSchema {
	if o == nil {
		var ret CharacterSchema
		return ret
	}

	return o.Character
}

// GetCharacterOk returns a tuple with the Character field value
// and a boolean to check if the value has been set.
func (o *CharacterFightDataSchema) GetCharacterOk() (*CharacterSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Character, true
}

// SetCharacter sets field value
func (o *CharacterFightDataSchema) SetCharacter(v CharacterSchema) {
	o.Character = v
}

func (o CharacterFightDataSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharacterFightDataSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cooldown"] = o.Cooldown
	toSerialize["fight"] = o.Fight
	toSerialize["character"] = o.Character
	return toSerialize, nil
}

func (o *CharacterFightDataSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cooldown",
		"fight",
		"character",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharacterFightDataSchema := _CharacterFightDataSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharacterFightDataSchema)

	if err != nil {
		return err
	}

	*o = CharacterFightDataSchema(varCharacterFightDataSchema)

	return err
}

type NullableCharacterFightDataSchema struct {
	value *CharacterFightDataSchema
	isSet bool
}

func (v NullableCharacterFightDataSchema) Get() *CharacterFightDataSchema {
	return v.value
}

func (v *NullableCharacterFightDataSchema) Set(val *CharacterFightDataSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacterFightDataSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacterFightDataSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacterFightDataSchema(val *CharacterFightDataSchema) *NullableCharacterFightDataSchema {
	return &NullableCharacterFightDataSchema{value: val, isSet: true}
}

func (v NullableCharacterFightDataSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacterFightDataSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


