/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GoldResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoldResponseSchema{}

// GoldResponseSchema struct for GoldResponseSchema
type GoldResponseSchema struct {
	Data GoldTransactionSchema `json:"data"`
}

type _GoldResponseSchema GoldResponseSchema

// NewGoldResponseSchema instantiates a new GoldResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoldResponseSchema(data GoldTransactionSchema) *GoldResponseSchema {
	this := GoldResponseSchema{}
	this.Data = data
	return &this
}

// NewGoldResponseSchemaWithDefaults instantiates a new GoldResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoldResponseSchemaWithDefaults() *GoldResponseSchema {
	this := GoldResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *GoldResponseSchema) GetData() GoldTransactionSchema {
	if o == nil {
		var ret GoldTransactionSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GoldResponseSchema) GetDataOk() (*GoldTransactionSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GoldResponseSchema) SetData(v GoldTransactionSchema) {
	o.Data = v
}

func (o GoldResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoldResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GoldResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoldResponseSchema := _GoldResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoldResponseSchema)

	if err != nil {
		return err
	}

	*o = GoldResponseSchema(varGoldResponseSchema)

	return err
}

type NullableGoldResponseSchema struct {
	value *GoldResponseSchema
	isSet bool
}

func (v NullableGoldResponseSchema) Get() *GoldResponseSchema {
	return v.value
}

func (v *NullableGoldResponseSchema) Set(val *GoldResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGoldResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGoldResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoldResponseSchema(val *GoldResponseSchema) *NullableGoldResponseSchema {
	return &NullableGoldResponseSchema{value: val, isSet: true}
}

func (v NullableGoldResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoldResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


