/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DestinationResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestinationResponseSchema{}

// DestinationResponseSchema struct for DestinationResponseSchema
type DestinationResponseSchema struct {
	// The name of the destination.
	Name string `json:"name"`
	// The x coordinate of the destination.
	X int32 `json:"x"`
	// The y coordinate of the destination.
	Y int32 `json:"y"`
	Content interface{} `json:"content"`
}

type _DestinationResponseSchema DestinationResponseSchema

// NewDestinationResponseSchema instantiates a new DestinationResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationResponseSchema(name string, x int32, y int32, content interface{}) *DestinationResponseSchema {
	this := DestinationResponseSchema{}
	this.Name = name
	this.X = x
	this.Y = y
	this.Content = content
	return &this
}

// NewDestinationResponseSchemaWithDefaults instantiates a new DestinationResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationResponseSchemaWithDefaults() *DestinationResponseSchema {
	this := DestinationResponseSchema{}
	return &this
}

// GetName returns the Name field value
func (o *DestinationResponseSchema) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DestinationResponseSchema) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DestinationResponseSchema) SetName(v string) {
	o.Name = v
}

// GetX returns the X field value
func (o *DestinationResponseSchema) GetX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *DestinationResponseSchema) GetXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *DestinationResponseSchema) SetX(v int32) {
	o.X = v
}

// GetY returns the Y field value
func (o *DestinationResponseSchema) GetY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *DestinationResponseSchema) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *DestinationResponseSchema) SetY(v int32) {
	o.Y = v
}

// GetContent returns the Content field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DestinationResponseSchema) GetContent() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DestinationResponseSchema) GetContentOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *DestinationResponseSchema) SetContent(v interface{}) {
	o.Content = v
}

func (o DestinationResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestinationResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

func (o *DestinationResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"x",
		"y",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDestinationResponseSchema := _DestinationResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDestinationResponseSchema)

	if err != nil {
		return err
	}

	*o = DestinationResponseSchema(varDestinationResponseSchema)

	return err
}

type NullableDestinationResponseSchema struct {
	value *DestinationResponseSchema
	isSet bool
}

func (v NullableDestinationResponseSchema) Get() *DestinationResponseSchema {
	return v.value
}

func (v *NullableDestinationResponseSchema) Set(val *DestinationResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationResponseSchema(val *DestinationResponseSchema) *NullableDestinationResponseSchema {
	return &NullableDestinationResponseSchema{value: val, isSet: true}
}

func (v NullableDestinationResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


