/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SkillDataSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkillDataSchema{}

// SkillDataSchema struct for SkillDataSchema
type SkillDataSchema struct {
	// Cooldown details.
	Cooldown CooldownSchema `json:"cooldown"`
	// Craft details.
	Details SkillInfoSchema `json:"details"`
	// Player details.
	Character CharacterSchema `json:"character"`
}

type _SkillDataSchema SkillDataSchema

// NewSkillDataSchema instantiates a new SkillDataSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkillDataSchema(cooldown CooldownSchema, details SkillInfoSchema, character CharacterSchema) *SkillDataSchema {
	this := SkillDataSchema{}
	this.Cooldown = cooldown
	this.Details = details
	this.Character = character
	return &this
}

// NewSkillDataSchemaWithDefaults instantiates a new SkillDataSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillDataSchemaWithDefaults() *SkillDataSchema {
	this := SkillDataSchema{}
	return &this
}

// GetCooldown returns the Cooldown field value
func (o *SkillDataSchema) GetCooldown() CooldownSchema {
	if o == nil {
		var ret CooldownSchema
		return ret
	}

	return o.Cooldown
}

// GetCooldownOk returns a tuple with the Cooldown field value
// and a boolean to check if the value has been set.
func (o *SkillDataSchema) GetCooldownOk() (*CooldownSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cooldown, true
}

// SetCooldown sets field value
func (o *SkillDataSchema) SetCooldown(v CooldownSchema) {
	o.Cooldown = v
}

// GetDetails returns the Details field value
func (o *SkillDataSchema) GetDetails() SkillInfoSchema {
	if o == nil {
		var ret SkillInfoSchema
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *SkillDataSchema) GetDetailsOk() (*SkillInfoSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *SkillDataSchema) SetDetails(v SkillInfoSchema) {
	o.Details = v
}

// GetCharacter returns the Character field value
func (o *SkillDataSchema) GetCharacter() CharacterSchema {
	if o == nil {
		var ret CharacterSchema
		return ret
	}

	return o.Character
}

// GetCharacterOk returns a tuple with the Character field value
// and a boolean to check if the value has been set.
func (o *SkillDataSchema) GetCharacterOk() (*CharacterSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Character, true
}

// SetCharacter sets field value
func (o *SkillDataSchema) SetCharacter(v CharacterSchema) {
	o.Character = v
}

func (o SkillDataSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkillDataSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cooldown"] = o.Cooldown
	toSerialize["details"] = o.Details
	toSerialize["character"] = o.Character
	return toSerialize, nil
}

func (o *SkillDataSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cooldown",
		"details",
		"character",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkillDataSchema := _SkillDataSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkillDataSchema)

	if err != nil {
		return err
	}

	*o = SkillDataSchema(varSkillDataSchema)

	return err
}

type NullableSkillDataSchema struct {
	value *SkillDataSchema
	isSet bool
}

func (v NullableSkillDataSchema) Get() *SkillDataSchema {
	return v.value
}

func (v *NullableSkillDataSchema) Set(val *SkillDataSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillDataSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillDataSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillDataSchema(val *SkillDataSchema) *NullableSkillDataSchema {
	return &NullableSkillDataSchema{value: val, isSet: true}
}

func (v NullableSkillDataSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillDataSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


