/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GoldBankResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoldBankResponseSchema{}

// GoldBankResponseSchema struct for GoldBankResponseSchema
type GoldBankResponseSchema struct {
	Data GoldSchema `json:"data"`
}

type _GoldBankResponseSchema GoldBankResponseSchema

// NewGoldBankResponseSchema instantiates a new GoldBankResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoldBankResponseSchema(data GoldSchema) *GoldBankResponseSchema {
	this := GoldBankResponseSchema{}
	this.Data = data
	return &this
}

// NewGoldBankResponseSchemaWithDefaults instantiates a new GoldBankResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoldBankResponseSchemaWithDefaults() *GoldBankResponseSchema {
	this := GoldBankResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *GoldBankResponseSchema) GetData() GoldSchema {
	if o == nil {
		var ret GoldSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GoldBankResponseSchema) GetDataOk() (*GoldSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GoldBankResponseSchema) SetData(v GoldSchema) {
	o.Data = v
}

func (o GoldBankResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoldBankResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GoldBankResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoldBankResponseSchema := _GoldBankResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoldBankResponseSchema)

	if err != nil {
		return err
	}

	*o = GoldBankResponseSchema(varGoldBankResponseSchema)

	return err
}

type NullableGoldBankResponseSchema struct {
	value *GoldBankResponseSchema
	isSet bool
}

func (v NullableGoldBankResponseSchema) Get() *GoldBankResponseSchema {
	return v.value
}

func (v *NullableGoldBankResponseSchema) Set(val *GoldBankResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGoldBankResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGoldBankResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoldBankResponseSchema(val *GoldBankResponseSchema) *NullableGoldBankResponseSchema {
	return &NullableGoldBankResponseSchema{value: val, isSet: true}
}

func (v NullableGoldBankResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoldBankResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


