/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecylingResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecylingResponseSchema{}

// RecylingResponseSchema struct for RecylingResponseSchema
type RecylingResponseSchema struct {
	Data RecyclingDataSchema `json:"data"`
}

type _RecylingResponseSchema RecylingResponseSchema

// NewRecylingResponseSchema instantiates a new RecylingResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecylingResponseSchema(data RecyclingDataSchema) *RecylingResponseSchema {
	this := RecylingResponseSchema{}
	this.Data = data
	return &this
}

// NewRecylingResponseSchemaWithDefaults instantiates a new RecylingResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecylingResponseSchemaWithDefaults() *RecylingResponseSchema {
	this := RecylingResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *RecylingResponseSchema) GetData() RecyclingDataSchema {
	if o == nil {
		var ret RecyclingDataSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RecylingResponseSchema) GetDataOk() (*RecyclingDataSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RecylingResponseSchema) SetData(v RecyclingDataSchema) {
	o.Data = v
}

func (o RecylingResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecylingResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RecylingResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecylingResponseSchema := _RecylingResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecylingResponseSchema)

	if err != nil {
		return err
	}

	*o = RecylingResponseSchema(varRecylingResponseSchema)

	return err
}

type NullableRecylingResponseSchema struct {
	value *RecylingResponseSchema
	isSet bool
}

func (v NullableRecylingResponseSchema) Get() *RecylingResponseSchema {
	return v.value
}

func (v *NullableRecylingResponseSchema) Set(val *RecylingResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableRecylingResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableRecylingResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecylingResponseSchema(val *RecylingResponseSchema) *NullableRecylingResponseSchema {
	return &NullableRecylingResponseSchema{value: val, isSet: true}
}

func (v NullableRecylingResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecylingResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


