/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EquipmentResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EquipmentResponseSchema{}

// EquipmentResponseSchema struct for EquipmentResponseSchema
type EquipmentResponseSchema struct {
	Data EquipRequestSchema `json:"data"`
}

type _EquipmentResponseSchema EquipmentResponseSchema

// NewEquipmentResponseSchema instantiates a new EquipmentResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEquipmentResponseSchema(data EquipRequestSchema) *EquipmentResponseSchema {
	this := EquipmentResponseSchema{}
	this.Data = data
	return &this
}

// NewEquipmentResponseSchemaWithDefaults instantiates a new EquipmentResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEquipmentResponseSchemaWithDefaults() *EquipmentResponseSchema {
	this := EquipmentResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *EquipmentResponseSchema) GetData() EquipRequestSchema {
	if o == nil {
		var ret EquipRequestSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EquipmentResponseSchema) GetDataOk() (*EquipRequestSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *EquipmentResponseSchema) SetData(v EquipRequestSchema) {
	o.Data = v
}

func (o EquipmentResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EquipmentResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *EquipmentResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEquipmentResponseSchema := _EquipmentResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEquipmentResponseSchema)

	if err != nil {
		return err
	}

	*o = EquipmentResponseSchema(varEquipmentResponseSchema)

	return err
}

type NullableEquipmentResponseSchema struct {
	value *EquipmentResponseSchema
	isSet bool
}

func (v NullableEquipmentResponseSchema) Get() *EquipmentResponseSchema {
	return v.value
}

func (v *NullableEquipmentResponseSchema) Set(val *EquipmentResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableEquipmentResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableEquipmentResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEquipmentResponseSchema(val *EquipmentResponseSchema) *NullableEquipmentResponseSchema {
	return &NullableEquipmentResponseSchema{value: val, isSet: true}
}

func (v NullableEquipmentResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEquipmentResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


