/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MonsterResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonsterResponseSchema{}

// MonsterResponseSchema struct for MonsterResponseSchema
type MonsterResponseSchema struct {
	Data MonsterSchema `json:"data"`
}

type _MonsterResponseSchema MonsterResponseSchema

// NewMonsterResponseSchema instantiates a new MonsterResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonsterResponseSchema(data MonsterSchema) *MonsterResponseSchema {
	this := MonsterResponseSchema{}
	this.Data = data
	return &this
}

// NewMonsterResponseSchemaWithDefaults instantiates a new MonsterResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonsterResponseSchemaWithDefaults() *MonsterResponseSchema {
	this := MonsterResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *MonsterResponseSchema) GetData() MonsterSchema {
	if o == nil {
		var ret MonsterSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MonsterResponseSchema) GetDataOk() (*MonsterSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *MonsterResponseSchema) SetData(v MonsterSchema) {
	o.Data = v
}

func (o MonsterResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonsterResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MonsterResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMonsterResponseSchema := _MonsterResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMonsterResponseSchema)

	if err != nil {
		return err
	}

	*o = MonsterResponseSchema(varMonsterResponseSchema)

	return err
}

type NullableMonsterResponseSchema struct {
	value *MonsterResponseSchema
	isSet bool
}

func (v NullableMonsterResponseSchema) Get() *MonsterResponseSchema {
	return v.value
}

func (v *NullableMonsterResponseSchema) Set(val *MonsterResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableMonsterResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableMonsterResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonsterResponseSchema(val *MonsterResponseSchema) *NullableMonsterResponseSchema {
	return &NullableMonsterResponseSchema{value: val, isSet: true}
}

func (v NullableMonsterResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonsterResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


