/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GETransactionSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GETransactionSchema{}

// GETransactionSchema struct for GETransactionSchema
type GETransactionSchema struct {
	// Item code.
	Item string `json:"item"`
	// Item quantity.
	Quantity int32 `json:"quantity"`
	// Item price.
	Price int32 `json:"price"`
	// Total price of the transaction.
	TotalPrice int32 `json:"total_price"`
}

type _GETransactionSchema GETransactionSchema

// NewGETransactionSchema instantiates a new GETransactionSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGETransactionSchema(item string, quantity int32, price int32, totalPrice int32) *GETransactionSchema {
	this := GETransactionSchema{}
	this.Item = item
	this.Quantity = quantity
	this.Price = price
	this.TotalPrice = totalPrice
	return &this
}

// NewGETransactionSchemaWithDefaults instantiates a new GETransactionSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGETransactionSchemaWithDefaults() *GETransactionSchema {
	this := GETransactionSchema{}
	return &this
}

// GetItem returns the Item field value
func (o *GETransactionSchema) GetItem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *GETransactionSchema) GetItemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *GETransactionSchema) SetItem(v string) {
	o.Item = v
}

// GetQuantity returns the Quantity field value
func (o *GETransactionSchema) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *GETransactionSchema) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *GETransactionSchema) SetQuantity(v int32) {
	o.Quantity = v
}

// GetPrice returns the Price field value
func (o *GETransactionSchema) GetPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *GETransactionSchema) GetPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *GETransactionSchema) SetPrice(v int32) {
	o.Price = v
}

// GetTotalPrice returns the TotalPrice field value
func (o *GETransactionSchema) GetTotalPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value
// and a boolean to check if the value has been set.
func (o *GETransactionSchema) GetTotalPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPrice, true
}

// SetTotalPrice sets field value
func (o *GETransactionSchema) SetTotalPrice(v int32) {
	o.TotalPrice = v
}

func (o GETransactionSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GETransactionSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["item"] = o.Item
	toSerialize["quantity"] = o.Quantity
	toSerialize["price"] = o.Price
	toSerialize["total_price"] = o.TotalPrice
	return toSerialize, nil
}

func (o *GETransactionSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"item",
		"quantity",
		"price",
		"total_price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGETransactionSchema := _GETransactionSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGETransactionSchema)

	if err != nil {
		return err
	}

	*o = GETransactionSchema(varGETransactionSchema)

	return err
}

type NullableGETransactionSchema struct {
	value *GETransactionSchema
	isSet bool
}

func (v NullableGETransactionSchema) Get() *GETransactionSchema {
	return v.value
}

func (v *NullableGETransactionSchema) Set(val *GETransactionSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGETransactionSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGETransactionSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGETransactionSchema(val *GETransactionSchema) *NullableGETransactionSchema {
	return &NullableGETransactionSchema{value: val, isSet: true}
}

func (v NullableGETransactionSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGETransactionSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


