/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GETransactionResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GETransactionResponseSchema{}

// GETransactionResponseSchema struct for GETransactionResponseSchema
type GETransactionResponseSchema struct {
	Data GETransactionListSchema `json:"data"`
}

type _GETransactionResponseSchema GETransactionResponseSchema

// NewGETransactionResponseSchema instantiates a new GETransactionResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGETransactionResponseSchema(data GETransactionListSchema) *GETransactionResponseSchema {
	this := GETransactionResponseSchema{}
	this.Data = data
	return &this
}

// NewGETransactionResponseSchemaWithDefaults instantiates a new GETransactionResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGETransactionResponseSchemaWithDefaults() *GETransactionResponseSchema {
	this := GETransactionResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *GETransactionResponseSchema) GetData() GETransactionListSchema {
	if o == nil {
		var ret GETransactionListSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GETransactionResponseSchema) GetDataOk() (*GETransactionListSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GETransactionResponseSchema) SetData(v GETransactionListSchema) {
	o.Data = v
}

func (o GETransactionResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GETransactionResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GETransactionResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGETransactionResponseSchema := _GETransactionResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGETransactionResponseSchema)

	if err != nil {
		return err
	}

	*o = GETransactionResponseSchema(varGETransactionResponseSchema)

	return err
}

type NullableGETransactionResponseSchema struct {
	value *GETransactionResponseSchema
	isSet bool
}

func (v NullableGETransactionResponseSchema) Get() *GETransactionResponseSchema {
	return v.value
}

func (v *NullableGETransactionResponseSchema) Set(val *GETransactionResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGETransactionResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGETransactionResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGETransactionResponseSchema(val *GETransactionResponseSchema) *NullableGETransactionResponseSchema {
	return &NullableGETransactionResponseSchema{value: val, isSet: true}
}

func (v NullableGETransactionResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGETransactionResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


