/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CharacterResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharacterResponseSchema{}

// CharacterResponseSchema struct for CharacterResponseSchema
type CharacterResponseSchema struct {
	Data CharacterSchema `json:"data"`
}

type _CharacterResponseSchema CharacterResponseSchema

// NewCharacterResponseSchema instantiates a new CharacterResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacterResponseSchema(data CharacterSchema) *CharacterResponseSchema {
	this := CharacterResponseSchema{}
	this.Data = data
	return &this
}

// NewCharacterResponseSchemaWithDefaults instantiates a new CharacterResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterResponseSchemaWithDefaults() *CharacterResponseSchema {
	this := CharacterResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *CharacterResponseSchema) GetData() CharacterSchema {
	if o == nil {
		var ret CharacterSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CharacterResponseSchema) GetDataOk() (*CharacterSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CharacterResponseSchema) SetData(v CharacterSchema) {
	o.Data = v
}

func (o CharacterResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharacterResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CharacterResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharacterResponseSchema := _CharacterResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharacterResponseSchema)

	if err != nil {
		return err
	}

	*o = CharacterResponseSchema(varCharacterResponseSchema)

	return err
}

type NullableCharacterResponseSchema struct {
	value *CharacterResponseSchema
	isSet bool
}

func (v NullableCharacterResponseSchema) Get() *CharacterResponseSchema {
	return v.value
}

func (v *NullableCharacterResponseSchema) Set(val *CharacterResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacterResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacterResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacterResponseSchema(val *CharacterResponseSchema) *NullableCharacterResponseSchema {
	return &NullableCharacterResponseSchema{value: val, isSet: true}
}

func (v NullableCharacterResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacterResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


