/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GoldTransactionSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoldTransactionSchema{}

// GoldTransactionSchema struct for GoldTransactionSchema
type GoldTransactionSchema struct {
	// Cooldown details.
	Cooldown CooldownSchema `json:"cooldown"`
	// Bank details.
	Bank GoldSchema `json:"bank"`
	// Player details.
	Character CharacterSchema `json:"character"`
}

type _GoldTransactionSchema GoldTransactionSchema

// NewGoldTransactionSchema instantiates a new GoldTransactionSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoldTransactionSchema(cooldown CooldownSchema, bank GoldSchema, character CharacterSchema) *GoldTransactionSchema {
	this := GoldTransactionSchema{}
	this.Cooldown = cooldown
	this.Bank = bank
	this.Character = character
	return &this
}

// NewGoldTransactionSchemaWithDefaults instantiates a new GoldTransactionSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoldTransactionSchemaWithDefaults() *GoldTransactionSchema {
	this := GoldTransactionSchema{}
	return &this
}

// GetCooldown returns the Cooldown field value
func (o *GoldTransactionSchema) GetCooldown() CooldownSchema {
	if o == nil {
		var ret CooldownSchema
		return ret
	}

	return o.Cooldown
}

// GetCooldownOk returns a tuple with the Cooldown field value
// and a boolean to check if the value has been set.
func (o *GoldTransactionSchema) GetCooldownOk() (*CooldownSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cooldown, true
}

// SetCooldown sets field value
func (o *GoldTransactionSchema) SetCooldown(v CooldownSchema) {
	o.Cooldown = v
}

// GetBank returns the Bank field value
func (o *GoldTransactionSchema) GetBank() GoldSchema {
	if o == nil {
		var ret GoldSchema
		return ret
	}

	return o.Bank
}

// GetBankOk returns a tuple with the Bank field value
// and a boolean to check if the value has been set.
func (o *GoldTransactionSchema) GetBankOk() (*GoldSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bank, true
}

// SetBank sets field value
func (o *GoldTransactionSchema) SetBank(v GoldSchema) {
	o.Bank = v
}

// GetCharacter returns the Character field value
func (o *GoldTransactionSchema) GetCharacter() CharacterSchema {
	if o == nil {
		var ret CharacterSchema
		return ret
	}

	return o.Character
}

// GetCharacterOk returns a tuple with the Character field value
// and a boolean to check if the value has been set.
func (o *GoldTransactionSchema) GetCharacterOk() (*CharacterSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Character, true
}

// SetCharacter sets field value
func (o *GoldTransactionSchema) SetCharacter(v CharacterSchema) {
	o.Character = v
}

func (o GoldTransactionSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoldTransactionSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cooldown"] = o.Cooldown
	toSerialize["bank"] = o.Bank
	toSerialize["character"] = o.Character
	return toSerialize, nil
}

func (o *GoldTransactionSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cooldown",
		"bank",
		"character",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoldTransactionSchema := _GoldTransactionSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoldTransactionSchema)

	if err != nil {
		return err
	}

	*o = GoldTransactionSchema(varGoldTransactionSchema)

	return err
}

type NullableGoldTransactionSchema struct {
	value *GoldTransactionSchema
	isSet bool
}

func (v NullableGoldTransactionSchema) Get() *GoldTransactionSchema {
	return v.value
}

func (v *NullableGoldTransactionSchema) Set(val *GoldTransactionSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGoldTransactionSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGoldTransactionSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoldTransactionSchema(val *GoldTransactionSchema) *NullableGoldTransactionSchema {
	return &NullableGoldTransactionSchema{value: val, isSet: true}
}

func (v NullableGoldTransactionSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoldTransactionSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


