/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecyclingItemsSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecyclingItemsSchema{}

// RecyclingItemsSchema struct for RecyclingItemsSchema
type RecyclingItemsSchema struct {
	// Objects received.
	Items []DropSchema `json:"items"`
}

type _RecyclingItemsSchema RecyclingItemsSchema

// NewRecyclingItemsSchema instantiates a new RecyclingItemsSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecyclingItemsSchema(items []DropSchema) *RecyclingItemsSchema {
	this := RecyclingItemsSchema{}
	this.Items = items
	return &this
}

// NewRecyclingItemsSchemaWithDefaults instantiates a new RecyclingItemsSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecyclingItemsSchemaWithDefaults() *RecyclingItemsSchema {
	this := RecyclingItemsSchema{}
	return &this
}

// GetItems returns the Items field value
func (o *RecyclingItemsSchema) GetItems() []DropSchema {
	if o == nil {
		var ret []DropSchema
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RecyclingItemsSchema) GetItemsOk() ([]DropSchema, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RecyclingItemsSchema) SetItems(v []DropSchema) {
	o.Items = v
}

func (o RecyclingItemsSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecyclingItemsSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *RecyclingItemsSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecyclingItemsSchema := _RecyclingItemsSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecyclingItemsSchema)

	if err != nil {
		return err
	}

	*o = RecyclingItemsSchema(varRecyclingItemsSchema)

	return err
}

type NullableRecyclingItemsSchema struct {
	value *RecyclingItemsSchema
	isSet bool
}

func (v NullableRecyclingItemsSchema) Get() *RecyclingItemsSchema {
	return v.value
}

func (v *NullableRecyclingItemsSchema) Set(val *RecyclingItemsSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableRecyclingItemsSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableRecyclingItemsSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecyclingItemsSchema(val *RecyclingItemsSchema) *NullableRecyclingItemsSchema {
	return &NullableRecyclingItemsSchema{value: val, isSet: true}
}

func (v NullableRecyclingItemsSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecyclingItemsSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


