/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GETransactionItemSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GETransactionItemSchema{}

// GETransactionItemSchema struct for GETransactionItemSchema
type GETransactionItemSchema struct {
	// Item code.
	Code string `json:"code" validate:"regexp=^[a-zA-Z0-9_-]+$"`
	// Item quantity.
	Quantity int32 `json:"quantity"`
	// Item price. Item price validation protects you if the price has changed since you last checked the buy/sale price of an item.
	Price int32 `json:"price"`
}

type _GETransactionItemSchema GETransactionItemSchema

// NewGETransactionItemSchema instantiates a new GETransactionItemSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGETransactionItemSchema(code string, quantity int32, price int32) *GETransactionItemSchema {
	this := GETransactionItemSchema{}
	this.Code = code
	this.Quantity = quantity
	this.Price = price
	return &this
}

// NewGETransactionItemSchemaWithDefaults instantiates a new GETransactionItemSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGETransactionItemSchemaWithDefaults() *GETransactionItemSchema {
	this := GETransactionItemSchema{}
	return &this
}

// GetCode returns the Code field value
func (o *GETransactionItemSchema) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GETransactionItemSchema) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GETransactionItemSchema) SetCode(v string) {
	o.Code = v
}

// GetQuantity returns the Quantity field value
func (o *GETransactionItemSchema) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *GETransactionItemSchema) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *GETransactionItemSchema) SetQuantity(v int32) {
	o.Quantity = v
}

// GetPrice returns the Price field value
func (o *GETransactionItemSchema) GetPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *GETransactionItemSchema) GetPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *GETransactionItemSchema) SetPrice(v int32) {
	o.Price = v
}

func (o GETransactionItemSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GETransactionItemSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["quantity"] = o.Quantity
	toSerialize["price"] = o.Price
	return toSerialize, nil
}

func (o *GETransactionItemSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"quantity",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGETransactionItemSchema := _GETransactionItemSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGETransactionItemSchema)

	if err != nil {
		return err
	}

	*o = GETransactionItemSchema(varGETransactionItemSchema)

	return err
}

type NullableGETransactionItemSchema struct {
	value *GETransactionItemSchema
	isSet bool
}

func (v NullableGETransactionItemSchema) Get() *GETransactionItemSchema {
	return v.value
}

func (v *NullableGETransactionItemSchema) Set(val *GETransactionItemSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGETransactionItemSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGETransactionItemSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGETransactionItemSchema(val *GETransactionItemSchema) *NullableGETransactionItemSchema {
	return &NullableGETransactionItemSchema{value: val, isSet: true}
}

func (v NullableGETransactionItemSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGETransactionItemSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


