/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseSchema{}

// ResponseSchema struct for ResponseSchema
type ResponseSchema struct {
	Message string `json:"message"`
}

type _ResponseSchema ResponseSchema

// NewResponseSchema instantiates a new ResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseSchema(message string) *ResponseSchema {
	this := ResponseSchema{}
	this.Message = message
	return &this
}

// NewResponseSchemaWithDefaults instantiates a new ResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseSchemaWithDefaults() *ResponseSchema {
	this := ResponseSchema{}
	return &this
}

// GetMessage returns the Message field value
func (o *ResponseSchema) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ResponseSchema) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ResponseSchema) SetMessage(v string) {
	o.Message = v
}

func (o ResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseSchema := _ResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseSchema)

	if err != nil {
		return err
	}

	*o = ResponseSchema(varResponseSchema)

	return err
}

type NullableResponseSchema struct {
	value *ResponseSchema
	isSet bool
}

func (v NullableResponseSchema) Get() *ResponseSchema {
	return v.value
}

func (v *NullableResponseSchema) Set(val *ResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseSchema(val *ResponseSchema) *NullableResponseSchema {
	return &NullableResponseSchema{value: val, isSet: true}
}

func (v NullableResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


