/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangePassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangePassword{}

// ChangePassword struct for ChangePassword
type ChangePassword struct {
	// Your password.
	Password string `json:"password" validate:"regexp=^[^\\\\s]+$"`
}

type _ChangePassword ChangePassword

// NewChangePassword instantiates a new ChangePassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangePassword(password string) *ChangePassword {
	this := ChangePassword{}
	this.Password = password
	return &this
}

// NewChangePasswordWithDefaults instantiates a new ChangePassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangePasswordWithDefaults() *ChangePassword {
	this := ChangePassword{}
	return &this
}

// GetPassword returns the Password field value
func (o *ChangePassword) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ChangePassword) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ChangePassword) SetPassword(v string) {
	o.Password = v
}

func (o ChangePassword) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangePassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *ChangePassword) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangePassword := _ChangePassword{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangePassword)

	if err != nil {
		return err
	}

	*o = ChangePassword(varChangePassword)

	return err
}

type NullableChangePassword struct {
	value *ChangePassword
	isSet bool
}

func (v NullableChangePassword) Get() *ChangePassword {
	return v.value
}

func (v *NullableChangePassword) Set(val *ChangePassword) {
	v.value = val
	v.isSet = true
}

func (v NullableChangePassword) IsSet() bool {
	return v.isSet
}

func (v *NullableChangePassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangePassword(val *ChangePassword) *NullableChangePassword {
	return &NullableChangePassword{value: val, isSet: true}
}

func (v NullableChangePassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangePassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


