/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MapResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapResponseSchema{}

// MapResponseSchema struct for MapResponseSchema
type MapResponseSchema struct {
	Data MapSchema `json:"data"`
}

type _MapResponseSchema MapResponseSchema

// NewMapResponseSchema instantiates a new MapResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapResponseSchema(data MapSchema) *MapResponseSchema {
	this := MapResponseSchema{}
	this.Data = data
	return &this
}

// NewMapResponseSchemaWithDefaults instantiates a new MapResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapResponseSchemaWithDefaults() *MapResponseSchema {
	this := MapResponseSchema{}
	return &this
}

// GetData returns the Data field value
func (o *MapResponseSchema) GetData() MapSchema {
	if o == nil {
		var ret MapSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MapResponseSchema) GetDataOk() (*MapSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *MapResponseSchema) SetData(v MapSchema) {
	o.Data = v
}

func (o MapResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MapResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMapResponseSchema := _MapResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMapResponseSchema)

	if err != nil {
		return err
	}

	*o = MapResponseSchema(varMapResponseSchema)

	return err
}

type NullableMapResponseSchema struct {
	value *MapResponseSchema
	isSet bool
}

func (v NullableMapResponseSchema) Get() *MapResponseSchema {
	return v.value
}

func (v *NullableMapResponseSchema) Set(val *MapResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableMapResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableMapResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapResponseSchema(val *MapResponseSchema) *NullableMapResponseSchema {
	return &NullableMapResponseSchema{value: val, isSet: true}
}

func (v NullableMapResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


