/*
Artifacts API

 Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

API version: 1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenResponseSchema{}

// TokenResponseSchema struct for TokenResponseSchema
type TokenResponseSchema struct {
	Token string `json:"token"`
}

type _TokenResponseSchema TokenResponseSchema

// NewTokenResponseSchema instantiates a new TokenResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenResponseSchema(token string) *TokenResponseSchema {
	this := TokenResponseSchema{}
	this.Token = token
	return &this
}

// NewTokenResponseSchemaWithDefaults instantiates a new TokenResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenResponseSchemaWithDefaults() *TokenResponseSchema {
	this := TokenResponseSchema{}
	return &this
}

// GetToken returns the Token field value
func (o *TokenResponseSchema) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *TokenResponseSchema) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *TokenResponseSchema) SetToken(v string) {
	o.Token = v
}

func (o TokenResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *TokenResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenResponseSchema := _TokenResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenResponseSchema)

	if err != nil {
		return err
	}

	*o = TokenResponseSchema(varTokenResponseSchema)

	return err
}

type NullableTokenResponseSchema struct {
	value *TokenResponseSchema
	isSet bool
}

func (v NullableTokenResponseSchema) Get() *TokenResponseSchema {
	return v.value
}

func (v *NullableTokenResponseSchema) Set(val *TokenResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenResponseSchema(val *TokenResponseSchema) *NullableTokenResponseSchema {
	return &NullableTokenResponseSchema{value: val, isSet: true}
}

func (v NullableTokenResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


